language: java
before_script:
- cat /dev/zero | ssh-keygen -q -N ""
- cat ~/.ssh/id_rsa.pub >> ~/.ssh/authorized_keys
- ssh -T travis@localhost exit
- echo $?
script: mvn clean test -B -DskipDisplay=true
