language: java
os:
- linux
- osx

osx_image: xcode9.3

addons:
  apt:
    packages:
    - pandoc

script:
- mvn clean test -B -DskipDisplay=true

after_failure:
- mvn surefire-report:report-only
- if [ $TRAVIS_OS_NAME = "osx" ]; then brew install pandoc; fi
- if [ $TRAVIS_OS_NAME = linux ]; then
     pandoc --columns 120 -t plain /home/travis/build/dmusican/Elegit/target/site/surefire-report.html;
  else
     pandoc --columns 120 -t plain /Users/travis/build/dmusican/Elegit/target/site/surefire-report.html;
  fi

after_success:
# jfx:native uses javafx-maven-plugin to run all tests and to build native install for particular OS running on
# jfx:build-jar uses javafx-maven-plugin to also produce executable jars
# assembly:single creates zips and compressed tarballs that contain all needed files
- mvn jfx:build-jar assembly:single
- if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then mvn jfx:build-native; fi


deploy:
-  provider: releases
   name: snapshot-release-linux
   api_key:
     secure: 2b50hjdUB1LJp+FlR5cMxA0cOfWSOsjbnyyVOb/ZFjCIqK+WFfLmANsJgVoDUiFx18i5x/Qy2IDpLErr9i5nQk0tkSR9EKyPqbnaX5XpbTiPbirBjQLuhnzSH+rti+AJhigufld0Pl+wTn5k6ppRFaG+k0xCM4SjcTZjzKcB4F/8X43WkAapjsmKu+tIFnPkjmx+7vif6uPm+5NDcTe8Xno0EOARgnJr4XUCm6A+iz6kRcXI2PApHVtyMt71BF/U6H0Vid4t41lTX0vw2zl7Aj+vGCWjVEiUyab+ZSHG6tuznkYLYQi3D9bVhCj2+tMuI6uP+AGlTcILKJsjBmsTw2hnMqJDGPb0wOH7/1FbhX/MIdHpjQssbOkuXoaFvl5TPE17M64KYvQvHv03NdEKOw4YnjYBAM2Iie/45aIsbKIm8/4/Z7kNWNPx7DH8m2LdyZSomKtJ9KRKfLPYrMPeV1XvGDKR0JoR4IL5j3G0XWqOM2VvS//VjQS+QzHnQRFK7ZGRikd7zPCItoGddOYP1Nvx2srj0j2XhhPTcl19gyFomYRKy+ZBlGj4Pa8hG5oHqU8ZfRHIt4u/jyk1oNHz3IQCag9wH6P//ukT6FdO25zIe7LcLrdWLM79mvHccMlni4XqdB8JMHxea3+tSxK2LPTPJ6Uhkb5xR1WB/0JyaEQ=
   file_glob: true
   file:
   - target/Elegit*SNAPSHOT*.zip
   - target/Elegit*SNAPSHOT*.gz
   - target/Elegit*SNAPSHOT*.bz2
   skip_cleanup: true
   draft: true
   on:
     tags: true
     condition: $TRAVIS_OS_NAME = linux
-  provider: releases
   name: snapshot-release-mac
   api_key:
     secure: 2b50hjdUB1LJp+FlR5cMxA0cOfWSOsjbnyyVOb/ZFjCIqK+WFfLmANsJgVoDUiFx18i5x/Qy2IDpLErr9i5nQk0tkSR9EKyPqbnaX5XpbTiPbirBjQLuhnzSH+rti+AJhigufld0Pl+wTn5k6ppRFaG+k0xCM4SjcTZjzKcB4F/8X43WkAapjsmKu+tIFnPkjmx+7vif6uPm+5NDcTe8Xno0EOARgnJr4XUCm6A+iz6kRcXI2PApHVtyMt71BF/U6H0Vid4t41lTX0vw2zl7Aj+vGCWjVEiUyab+ZSHG6tuznkYLYQi3D9bVhCj2+tMuI6uP+AGlTcILKJsjBmsTw2hnMqJDGPb0wOH7/1FbhX/MIdHpjQssbOkuXoaFvl5TPE17M64KYvQvHv03NdEKOw4YnjYBAM2Iie/45aIsbKIm8/4/Z7kNWNPx7DH8m2LdyZSomKtJ9KRKfLPYrMPeV1XvGDKR0JoR4IL5j3G0XWqOM2VvS//VjQS+QzHnQRFK7ZGRikd7zPCItoGddOYP1Nvx2srj0j2XhhPTcl19gyFomYRKy+ZBlGj4Pa8hG5oHqU8ZfRHIt4u/jyk1oNHz3IQCag9wH6P//ukT6FdO25zIe7LcLrdWLM79mvHccMlni4XqdB8JMHxea3+tSxK2LPTPJ6Uhkb5xR1WB/0JyaEQ=
   file_glob: true
   file:
   - target/jfx/native/*.pkg
   - target/jfx/native/*.dmg
   skip_cleanup: true
   draft: true
   on:
     tags: true
     condition: $TRAVIS_OS_NAME = osx
